# v2 sintax
version: '2'

# Named volumes
volumes:
  # MySQL Data
#  devrocks-mysql-data:
#    driver: local

  # postgresql
  devrocks-pgsql-data:
    driver: local

  # Redis Data
  devrocks-redis-data:
    driver: local

services:
  # MySQL (5.7)
#  mysql:
#    image: mysql:5.7
#    container_name: devrocks-mysql
#    volumes:
#      - devrocks-mysql-data:/var/lib/mysql
#    ports:
#      - "3306:3306"
#    environment:
#      - MYSQL_ROOT_PASSWORD=devrocks
#      - MYSQL_DATABASE=devrocks
#      - MYSQL_USER=devrocks
#      - MYSQL_PASSWORD=devrocks

  # Postresql (Alpine)
  postgres:
    image: postgres:alpine
    container_name: devrocks-pgsql
    volumes:
      - devrocks-pgsql-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=devrocks
      - POSTGRES_USER=devrocks
      - POSTGRES_PASSWORD=devrocks

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: devrocks-redis
    command: --appendonly yes
    volumes:
      - devrocks-redis-data:/data
    ports:
      - "6379:6379"

  # APP (with Caddy)
  app:
    image: ambientum/php:7.0-caddy
    container_name: devrocks-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - postgres
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: devrocks-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - postgres
      - cache
